xDoc: true  # 是否启用
xDocPath: #src\main\java\com\api\showDoc\controller\
paramLevel: 4 # 解析实体类层级数
respbodyLevel: 2 # 解析返回示例实体类层级数
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8085
spring:
    resources: # 指定静态资源的路径
        static-locations: classpath:/xdoc/