xdoc:
  enable: true  # 是否启用
  sourcePath: src\main\java\com\api\showDoc\controller\
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8085
spring:
    resources: # 指定静态资源的路径
        static-locations: classpath:/xdoc/